#!/bin/bash -x

aclocal;
autoconf -f ./configure_mc.ac > ./configure;
chmod u+x ./configure;
automake -f ./Makefile_mc;
./configure;
make -f ./Makefile_mc clean;
make -f ./Makefile_mc putversion;
make -f ./Makefile_mc;
